version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
shallow_clone: true
clone_depth: 1
environment:
  my_secret:
    secure: OK4Ru5U1BaO5PzLhlmjEIg==
services:
- iis
- mssql2017
build_script:
- ps: .\build\build.ps1 appveyor -createArtifacts -installSitecore -buildSolution -deploySolution -SqlAdminUser sa -SqlAdminPassword "Password12!" -adminPassword c -Configuration Release
test:
  assemblies:
  - src\**\DevOps.AppVeyor.Tests.*.dll
cache:
  - c:\downloads
artifacts:
- path: output\Files.zip
  name: Files
on_failure:
- ps: '$blockRdp = $true; iex ((new-object net.webclient).DownloadString(''https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1''))'